on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
    - name: checkout source repo
      uses: actions/checkout@stage

    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        python-root: './main.py'
        flake8-flags: ''
        mypy-flags: ''
        fail-on-isort: false
        skip-flake8: true
        skip-mypy: true