name: Prod <- Stage CI
on:
  pull_request:
    branches: master

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CD workflow
    steps:

    - name: Merge stage -> master
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: staging
        target_branch: master
        github_token: ${{ github.token }}